apiVersion: apps/v1

kind: Deployment

metadata:
  name: flask-app-green
  namespace: devsecops-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-app
      version: green

  template:
    metadata:
      labels:
        app: flask-app
        version: green

    spec:
      containers:
        - name: flask-app
          image: itisscdac/devsecops-flask-app:272b2f8cf02c36edb53a5e5f0909bf32010200da
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
          
          env:
          - name: APP_VERSION
            value: "green"
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ENVIRONMENT

          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 5
            periodSeconds: 5
